data_pipeline:
  outputs:
    dev:
      account: "<ACCOUNT_LOCATOR>-<ACCOUNT_NAME>"
      database: dbt_db
      password: "<SF_PASSWORD>"
      role: dbt_role
      schema: dbt_schema
      threads: 10
      type: snowflake
      user: "<SF_USERNAME>"
      warehouse: dbt_wh
  target: dev
